name: CI/CD Pipeline - Backend Express

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      ###################################
      # BACKEND - EXPRESS
      ###################################
      - name: Instalar dependências do backend
        working-directory: ./versao-final/backend
        run: npm install

      - name: Rodar testes do backend
        working-directory: ./versao-final/backend
        env:
          AUTH_SECRET: "abc"
        run: npm test  
