name: Provision S3 Static Site

on:
  issues:
    types:
      - opened

jobs:
  provision_s3_static_site:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.5.0"

    - name: Extract Bucket Name from Issue
      run: |
        bucket_name="${{ github.event.issue.title }}"
        echo "Bucket name from issue title: $bucket_name"
        echo "bucket_name=$bucket_name" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform -chdir=infra/s3-bucket-static init

    - name: Terraform Plan
      run: terraform -chdir=infra/s3-bucket-static plan -var "bucket_name=${{ env.bucket_name }}" -out=tfplan

    - name: Terraform Apply
      run: terraform -chdir=infra/s3-bucket-static apply -auto-approve tfplan

    - name: Output Website URL
      run: echo "Website URL: $(terraform -chdir=infra/s3-bucket-static output -raw website_url)"

    - name: Add comment to issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue comment ${{ github.event.issue.number }} \
          --repo ${{ github.repository }} \
          --body "Bucket provisionado com sucesso com nome: **${{ env.bucket_name }}**"
