name: Provision Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Executa o workflow apenas se houver mudanças no diretório do backend
      - '.github/workflows/provision-elastic-beanstalk.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Inicializar Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: ./infra/elastic-beanstalk

    # Aplicar Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve -var="mongodb_uri=${{ secrets.MONGODB_URI }}"
      working-directory: ./infra/elastic-beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    # Criar ZIP do backend
    - name: Create ZIP for Elastic Beanstalk
      run: |
        cd backend
        zip -r ../app.zip .
      working-directory: .

    # Fazer upload do ZIP para o Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
        application_name: knowledge-backend
        environment_name: knowledge-backend-env
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: app.zip